###
POST https://a08dcj63k0.execute-api.us-east-1.amazonaws.com/dev/book/add

{
  "name": "Sapiens",
  "releaseDate": 321,
  "authorName": "Yuval Harari"
}

###
POST https://a08dcj63k0.execute-api.us-east-1.amazonaws.com/dev/book/5b2c64d0-00ec-11eb-8b5b-c5f169a46a40/update

###
POST https://a08dcj63k0.execute-api.us-east-1.amazonaws.com/dev/book/5b2c64d0-00ec-11eb-8b5b-c5f169a46a40/delete

### 
GET https://a08dcj63k0.execute-api.us-east-1.amazonaws.com/dev/book/5b2c64d0-00ec-11eb-8b5b-c5f169a46a40

### 
GET https://a08dcj63k0.execute-api.us-east-1.amazonaws.com/dev/books